export const sliderItems = [
    {
      id: "L5ohc75VIqPr38QEBqhv",
      img: "https://cdn.dribbble.com/users/5332454/screenshots/14512350/poster__2_4x.png",
      title: "Casa des artes Dé FAMALICAO",
      desc: "Watch some random guy get shot by two arrows. Maybe he needs some help. Or you can help me on this RWP.",
      bg: "f5fafd",
      artist: "Shahriman sensei",
      startDate: "Friday 05 Feb 2022",
      price: "18.00",
    },
    {
      id: 2,
      img: "https://gordonator.files.wordpress.com/2018/10/c3afasg_ila.jpg",
      title: "C3AFA I <3 Anisong 2018",
      desc: "Wew can't wait to cheer for my darling Rie san <3. Other than the best girl in the universe Rieri, never heard of any other artist performing in this event.",
      bg: "fcf1ed",
    },
    {
      id: 3,
      img: "https://anotemusic.com/wp-content/uploads/2021/04/27042021-ANote-Music-breaks-into-Japan-with-Royalty-Bank-partnership.001.jpeg",
      title: "Not Sure WHAT EVENT is this",
      desc: "Some random chicks hitting drums like how your mum whack your ass. Haiya just joking don't be angry.",
      bg: "fbf0f4",
    },
    {
        id: 4,
        img: "https://www.wxxi.org/sites/default/files/images/highlights/bocelli20music20hope20rotator.jpg",
        title: "Music for HOPE by Andrea Bocelli",
        desc: "When I listen to Andrea Bocelli, my entire body achieve inner peace and the world happiness level increase by 1%.",
        bg: "fbf0f4",
      },
      {
        id: 5,
        img: "https://www.tallahasseearts.org/wp-content/uploads/sites/www.tallahasseearts.org/images/2021/12/event-featured-the-first-first-friday-of-2022-1639246267.png",
        title: "First Friday ART, MUSIC, and MORE!",
        desc: "First Friday? I'm not sure how many Friday I've been through since I born. Now you reminded me how old I am now, so sad. Now world happiness level decrease by 1%.",
        bg: "fbf0f4",
      },
      {
        id: 6,
        img: "https://s3.ap-south-1.amazonaws.com/townscript-production/images/8191c0a0-60b1-437f-a08b-2f7160f43f71.jpg",
        title: "First Friday on TIARA EVE BOYD FLIP",
        desc: "Haiya why same event again?? I don't care liao la, I want to sleep ady, no one gonna look at the description anyway.",
        bg: "fbf0f4",
      },
      {
        id: 1,
        img: "https://cdn.dribbble.com/users/5332454/screenshots/14512350/poster__2_4x.png",
        title: "Casa des artes Dé FAMALICAO",
        desc: "Watch some random guy get shot by two arrows. Maybe he needs some help. Or you can help me on this RWP.",
        bg: "f5fafd",
      },
      {
        id: 2,
        img: "https://gordonator.files.wordpress.com/2018/10/c3afasg_ila.jpg",
        title: "C3AFA I <3 Anisong 2018",
        desc: "Wew can't wait to cheer for my darling Rie san <3. Other than the best girl in the universe Rieri, never heard of any other artist performing in this event.",
        bg: "fcf1ed",
      },
      {
        id: 3,
        img: "https://anotemusic.com/wp-content/uploads/2021/04/27042021-ANote-Music-breaks-into-Japan-with-Royalty-Bank-partnership.001.jpeg",
        title: "Not Sure WHAT EVENT is this",
        desc: "Some random chicks hitting drums like how your mum whack your ass. Haiya just joking don't be angry.",
        bg: "fbf0f4",
      },
      {
          id: 4,
          img: "https://www.wxxi.org/sites/default/files/images/highlights/bocelli20music20hope20rotator.jpg",
          title: "Music for HOPE by Andrea Bocelli",
          desc: "When I listen to Andrea Bocelli, my entire body achieve inner peace and the world happiness level increase by 1%.",
          bg: "fbf0f4",
        },
        {
          id: 5,
          img: "https://www.tallahasseearts.org/wp-content/uploads/sites/www.tallahasseearts.org/images/2021/12/event-featured-the-first-first-friday-of-2022-1639246267.png",
          title: "First Friday ART, MUSIC, and MORE!",
          desc: "First Friday? I'm not sure how many Friday I've been through since I born. Now you reminded me how old I am now, so sad. Now world happiness level decrease by 1%.",
          bg: "fbf0f4",
        },
        {
          id: 6,
          img: "https://s3.ap-south-1.amazonaws.com/townscript-production/images/8191c0a0-60b1-437f-a08b-2f7160f43f71.jpg",
          title: "First Friday on TIARA EVE BOYD FLIP",
          desc: "Haiya why same event again?? I don't care liao la, I want to sleep ady, no one gonna look at the description anyway.",
          bg: "fbf0f4",
        },
        {
          id: 1,
          img: "https://cdn.dribbble.com/users/5332454/screenshots/14512350/poster__2_4x.png",
          title: "Casa des artes Dé FAMALICAO",
          desc: "Watch some random guy get shot by two arrows. Maybe he needs some help. Or you can help me on this RWP.",
          bg: "f5fafd",
        },
        {
          id: 2,
          img: "https://gordonator.files.wordpress.com/2018/10/c3afasg_ila.jpg",
          title: "C3AFA I <3 Anisong 2018",
          desc: "Wew can't wait to cheer for my darling Rie san <3. Other than the best girl in the universe Rieri, never heard of any other artist performing in this event.",
          bg: "fcf1ed",
        },
        {
          id: 3,
          img: "https://anotemusic.com/wp-content/uploads/2021/04/27042021-ANote-Music-breaks-into-Japan-with-Royalty-Bank-partnership.001.jpeg",
          title: "Not Sure WHAT EVENT is this",
          desc: "Some random chicks hitting drums like how your mum whack your ass. Haiya just joking don't be angry.",
          bg: "fbf0f4",
        },
        {
            id: 4,
            img: "https://www.wxxi.org/sites/default/files/images/highlights/bocelli20music20hope20rotator.jpg",
            title: "Music for HOPE by Andrea Bocelli",
            desc: "When I listen to Andrea Bocelli, my entire body achieve inner peace and the world happiness level increase by 1%.",
            bg: "fbf0f4",
          },
          {
            id: 5,
            img: "https://www.tallahasseearts.org/wp-content/uploads/sites/www.tallahasseearts.org/images/2021/12/event-featured-the-first-first-friday-of-2022-1639246267.png",
            title: "First Friday ART, MUSIC, and MORE!",
            desc: "First Friday? I'm not sure how many Friday I've been through since I born. Now you reminded me how old I am now, so sad. Now world happiness level decrease by 1%.",
            bg: "fbf0f4",
          },
          {
            id: 6,
            img: "https://s3.ap-south-1.amazonaws.com/townscript-production/images/8191c0a0-60b1-437f-a08b-2f7160f43f71.jpg",
            title: "First Friday on TIARA EVE BOYD FLIP",
            desc: "Haiya why same event again?? I don't care liao la, I want to sleep ady, no one gonna look at the description anyway.",
            bg: "fbf0f4",
          },
  ];

  export const categories = [
    {
      id: 1,
      img: "https://www.themoviedb.org/t/p/original/5KSpLDRaUcIDPU670AF4enwpkAr.jpg",
      title: "伊藤美来",
    },
    {
      id: 2,
      img: "https://i.pinimg.com/750x/8a/d8/82/8ad882e3368571f880250b4e78ae751c.jpg",
      title: "高橋リエ",
    },
    {
      id: 3,
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRYg0L5Ab3W9GiIzipnrzDclKi0QkaQX-akYQ&usqp=CAU",
      title: "水瀬祈り",
    },
    {
        id: 3,
        img: "https://imagecdn.me/star/zhang-karlina.png",
        title: "Karlina ZHANG",
      },
      {
        id: 3,
        img: "https://dynamicmedia.livenationinternational.com/Media/n/n/b/38b70da9-9fd3-44df-9a6a-16c4bfe5e93d.jpg",
        title: "Rainie YANG",
      },
  ];
